---
# Copyright: (c) 2024, Benoit DE RANCOURT <benoit2r@gmail.com>
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

namespace: bderancourt
name: openwrt
version: 1.0.0
readme: README.md
authors:
  - Benoit DE RANCOURT <benoit2r@gmail.com>
description: >-
    This repo contains the bderancourt.openwrt Ansible Collection.
    The collection includes modules to work with OpenWRT.
license_file: LICENCE
tags:
  - networking
  - security
  - firewall
  - openwrt
  - uci
repository: https://github.com/bderancourt/ansible-openwrt
documentation: https://github.com/bderancourt/ansible-openwrt/README.md
homepage: https://github.com/bderancourt/ansible-openwrt
issues: https://github.com/bderancourt/ansible-openwrt/issues
build_ignore: ['.vscode', '*.bash']
