name: Test Ansible collection
on: [push]
jobs:
  test:
    name: Ansible test
    runs-on: ubuntu-latest
    steps:
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@v1.14.1
        with:
          ansible-core-version: stable-2.16
          testing-type: sanity
