name: Test Ansible collection
on: [push]
jobs:
  steps:
    - name: Perform sanity testing with ansible-test
      runs-on: ubuntu-latest
      uses: ansible-community/ansible-test-gh-action@v1.14.1
      with:
        ansible-core-version: stable-2.16
        testing-type: sanity
